export const locationList = [
  {value: "Abilene"},
  {value: "ACE - Carson"},
  {value: "ACE - Perris"},
  {value: "Adamsburg"},
  {value: "ADESA Boston"},
  {value: "ADESA Great Lakes"},
  {value: "ADESA New Jersey"},
  {value: "Adesa PA"},
  {value: "ADESA Sioux Falls"},
  {value: "ADESA Wisconsin"},
  {value: "Akron - Canton"},
  {value: "Albany"},
  {value: "Albuquerque"},
  {value: "Altoona"},
  {value: "Amarillo"},
  {value: "Anaheim"},
  {value: "Anchorage"},
  {value: "Andrews"},
  {value: "Antelope"},
  {value: "Appleton"},
  {value: "Arizona Auto Auction"},
  {value: "Asheville"},
  {value: "Ashland"},
  {value: "Atlanta Auto Auction"},
  {value: "Atlanta East"},
  {value: "Atlanta North"},
  {value: "Atlanta South"},
  {value: "Atlanta West"},
  {value: "Augusta"},
  {value: "Austin"},
  {value: "Avenel New Jersey"},
  {value: "Bakersfield"},
  {value: "Baltimor"},
  {value: "Bangor"},
  {value: "Baton Rouge"},
  {value: "Bay Area"},
  {value: "Bel - Air Auto Auction"},
  {value: "Billings"},
  {value: "Birmingham"},
  {value: "Boise"},
  {value: "Boston"},
  {value: "Boston - Shirley"},
  {value: "Bowlimg Green"},
  {value: "Bridgeport"},
  {value: "Bridgeview"},
  {value: "Buckhannon"},
  {value: "Buffalo"},
  {value: "Burlington"},
  {value: "Candia"},
  {value: "Cartersville"},
  {value: "Casper"},
  {value: "Central Auto Auction"},
  {value: "Central New Jersey"},
  {value: "Chambersburg"},
  {value: "Charleston - SC"},
  {value: "Charleston - WV"},
  {value: "Charlotte"},
  {value: "Chattanooga"},
  {value: "Chicago North"},
  {value: "Chicago South"},
  {value: "Chicago West"},
  {value: "China Grove"},
  {value: "Cicero"},
  {value: "Cincinnati"},
  {value: "Clayton"},
  {value: "Clearwater"},
  {value: "Cleveland"},
  {value: "Cleveland East"},
  {value: "Cleveland West"},
  {value: "Clinton"},
  {value: "Colorado Springs"},
  {value: "Columbia MO"},
  {value: "Columbia SC"},
  {value: "Columbus AL"},
  {value: "Columbus OH"},
  {value: "Concord"},
  {value: "Corpus Christi"},
  {value: "Culpeper, VA"},
  {value: "Dallas"},
  {value: "Dallas South"},
  {value: "Danville"},
  {value: "Davenport"},
  {value: "Dayton"},
  {value: "Defuniak Springs"},
  {value: "Denver"},
  {value: "Denver South"},
  {value: "Des Moines"},
  {value: "Detroit"},
  {value: "Dothan"},
  {value: "Dundalk"},
  {value: "East Bay"},
  {value: "East NC"},
  {value: "El Paso"},
  {value: "Eldridge"},
  {value: "Englishtown"},
  {value: "Erie"},
  {value: "Essex"},
  {value: "Eugene"},
  {value: "Exeter"},
  {value: "Fargo"},
  {value: "Fayetteville"},
  {value: "Flint"},
  {value: "Florence"},
  {value: "Fontana"},
  {value: "Fort Myers"},
  {value: "Fort Wayne"},
  {value: "Fort Worth North"},
  {value: "Four Oaks, NC"},
  {value: "Fredericksburg - South"},
  {value: "Fremont"},
  {value: "Fresno"},
  {value: "Ft. Pierce"},
  {value: "Ft. Worth"},
  {value: "Ft. Lauderdale"},
  {value: "Glassboro East"},
  {value: "Glassboro West"},
  {value: "Golden Gate"},
  {value: "Gr. Rapids"},
  {value: "Graham"},
  {value: "Grand Island"},
  {value: "Grantville"},
  {value: "Greater Auto Auction Phoenix"},
  {value: "Greensboro"},
  {value: "Greenville"},
  {value: "Greer"},
  {value: "Grenada"},
  {value: "Gulf Coast"},
  {value: "Gulfport"},
  {value: "Hammond"},
  {value: "Hampton, VA"},
  {value: "Harrisburg"},
  {value: "Harrisonburg Auto Auction"},
  {value: "Hartford"},
  {value: "Hartford City"},
  {value: "Hartford - South"},
  {value: "Hatward"},
  {value: "Hayward"},
  {value: "Helena"},
  {value: "High Desert"},
  {value: "Honolulu"},
  {value: "Houston"},
  {value: "Houston-North"},
  {value: "Huntsville"},
  {value: "Indianapolis"},
  {value: "Ionia"},
  {value: "Jackson"},
  {value: "Jacksonville"},
  {value: "Jacksonville East"},
  {value: "Jacksonville West"},
  {value: "Kansas City"},
  {value: "Kincheloe"},
  {value: "Knoxville"},
  {value: "Lafayette"},
  {value: "Lansing"},
  {value: "Las Vegas"},
  {value: "Laurel"},
  {value: "Lexington East KY"},
  {value: "Lexington SC"},
  {value: "Lexington West KY"},
  {value: "Lincoln, IL"},
  {value: "Lincoln, NE"},
  {value: "Little Rock"},
  {value: "Long Beach"},
  {value: "Long Island"},
  {value: "Longview"},
  {value: "Los Angeles"},
  {value: "Los Angeles - Adesa"},
  {value: "Louisville"},
  {value: "Lubbock"},
  {value: "Lufkin"},
  {value: "Lumberton"},
  {value: "Lyman"},
  {value: "Macon"},
  {value: "Madison"},
  {value: "Madison Heights"},
  {value: "Manchester"},
  {value: "Manheim Albany"},
  {value: "Manheim Arena Illinois"},
  {value: "Manheim Arizona"},
  {value: "Manheim Auto Auction"},
  {value: "Manheim Baltimore - Washington"},
  {value: "Manheim Bishop Brothers"},
  {value: "Manheim California"},
  {value: "Manheim Carleton"},
  {value: "Manheim Central California"},
  {value: "Manheim Central Florida"},
  {value: "Manheim Chicago"},
  {value: "Manheim Cincinnati"},
  {value: "Manheim Colorado"},
  {value: "Manheim Dallas-Ft Worth"},
  {value: "Manheim Darlington"},
  {value: "Manheim Daytona Beach"},
  {value: "Manheim Denver"},
  {value: "Manheim Detroit"},
  {value: "Manheim Fort Lauderdale"},
  {value: "Manheim Fort Myers"},
  {value: "Manheim Fort Wayne"},
  {value: "Manheim Fredericksburg"},
  {value: "Manheim Gateway St Louis"},
  {value: "Manheim Georgia"},
  {value: "Manheim Imperial Auto Auction"},
  {value: "Manheim Kentucky"},
  {value: "Manheim Lafayette"},
  {value: "Manheim Lakeland"},
  {value: "Manheim Metro Dallas"},
  {value: "Manheim Metro Milwaukee"},
  {value: "Manheim Milwaukee"},
  {value: "Manheim Mississippi"},
  {value: "Manheim Missouri"},
  {value: "Manheim Nashville"},
  {value: "Manheim Nevada"},
  {value: "Manheim New England"},
  {value: "Manheim New Jersey"},
  {value: "Manheim New Mexico"},
  {value: "Manheim New Orleans"},
  {value: "Manheim New York"},
  {value: "Manheim North Carolina"},
  {value: "Manheim Northstar Minnesota"},
  {value: "Manheim Ohio"},
  {value: "Manheim Oklahoma City"},
  {value: "Manheim Orlando"},
  {value: "MANHEIM PALM BEACH"},
  {value: "Manheim Pennsylvania"},
  {value: "Manheim Pensacola"},
  {value: "Manheim Philadelphia"},
  {value: "Manheim Phoenix"},
  {value: "Manheim Pittsburg"},
  {value: "Manheim Riverside"},
  {value: "Manheim San Antonio"},
  {value: "Manheim San Diego"},
  {value: "Manheim San Francisco Bay"},
  {value: "Manheim Seattle"},
  {value: "Manheim Skyline Auto Auction"},
  {value: "Manheim Southern California"},
  {value: "Manheim St.Pete"},
  {value: "Manheim Statesville"},
  {value: "MANHEIM TAMPA"},
  {value: "Manheim Tennessee"},
  {value: "Manheim Texas Hobby"},
  {value: "Manheim Utah"},
  {value: "Manheim Virginia(FREDERICKSBURG)"},
  {value: "Martinez"},
  {value: "MCAllen"},
  {value: "Mebane"},
  {value: "Memphis"},
  {value: "Metro DC"},
  {value: "Miami"},
  {value: "Miami Central"},
  {value: "Miami North"},
  {value: "Miami South"},
  {value: "Middletown"},
  {value: "Milwaukee"},
  {value: "Minneapolis"},
  {value: "Minneapolis / St.Paul"},
  {value: "Minneapolis North"},
  {value: "Missoula"},
  {value: "Mobile"},
  {value: "Mocksville"},
  {value: "Montgomery"},
  {value: "Nashville"},
  {value: "National Auto Dealers Exchange"},
  {value: "New Castle"},
  {value: "New Orleans"},
  {value: "Newburgh"},
  {value: "North Boston"},
  {value: "North Charleston - SC"},
  {value: "North Hollywood"},
  {value: "North Seattle"},
  {value: "Northern New Jersey"},
  {value: "Northern Virginia"},
  {value: "Ocala"},
  {value: "Ogden"},
  {value: "Oklahoma City"},
  {value: "Omaha"},
  {value: "Orlando"},
  {value: "Orlando North"},
  {value: "Orlando South"},
  {value: "Paducah"},
  {value: "Pasco"},
  {value: "Pensacola"},
  {value: "Peoria"},
  {value: "Permian Basin"},
  {value: "Philadelphia"},
  {value: "Philadelphia East"},
  {value: "Phoenix"},
  {value: "Pittsburg"},
  {value: "Pittsburgh South"},
  {value: "Portage"},
  {value: "Portland"},
  {value: "Portland - Gorham"},
  {value: "Portland North"},
  {value: "Portland South"},
  {value: "Portland West"},
  {value: "Providence"},
  {value: "Pulaski"},
  {value: "Punta Gorda"},
  {value: "Puyallup"},
  {value: "Raleigh"},
  {value: "Rancho Cucamonga"},
  {value: "Redding"},
  {value: "Reno"},
  {value: "Richmond"},
  {value: "Riverside"},
  {value: "Roanoke"},
  {value: "Rochester"},
  {value: "Rosedale"},
  {value: "Sacramento"},
  {value: "Salisbury"},
  {value: "Salt Lake City"},
  {value: "San Antonio"},
  {value: "San Bernardino"},
  {value: "San Diego"},
  {value: "San Jose"},
  {value: "Sarasota"},
  {value: "Savannah"},
  {value: "Scranton"},
  {value: "Seaford"},
  {value: "Seattle"},
  {value: "Shady Spring, WV"},
  {value: "Shreveport"},
  {value: "Sikeston"},
  {value: "Sioux Falls"},
  {value: "So Sacramento"},
  {value: "Somerville"},
  {value: "South Bend"},
  {value: "South Boston"},
  {value: "Southern Illinois"},
  {value: "Southern New Jersey"},
  {value: "Spartanburg"},
  {value: "Spokane"},
  {value: "Springfield"},
  {value: "St.Cloud"},
  {value: "St. Louis"},
  {value: "Suffolk"},
  {value: "Sun Valley"},
  {value: "Syracuse"},
  {value: "Tallahassee"},
  {value: "Tampa"},
  {value: "Tampa South"},
  {value: "Tanner"},
  {value: "Taunton"},
  {value: "Templeton"},
  {value: "Tidewater"},
  {value: "Tifton"},
  {value: "TOTAL RESOURCE AUC CENTRL PENN"},
  {value: "Trenton"},
  {value: "Tucson"},
  {value: "Tulsa"},
  {value: "Vallejo"},
  {value: "Van Nuys"},
  {value: "Waco"},
  {value: "Walton"},
  {value: "WashingtonDC"},
  {value: "Webster"},
  {value: "West Palm Beach"},
  {value: "West Warren"},
  {value: "Western Colorado"},
  {value: "Wheeling"},
  {value: "Wichita"},
  {value: "Wilmington"},
  {value: "York Haven"},
  {value: "York Springs"}
];
